In [10]:
#from google.colab import drive
#drive.mount('/content/drive')

In [11]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


In [12]:
# Load the training data
class_data = pd.read_csv(r'C:\Users\macks\Project 4\Zoo_Data_Project\Resources\class.csv')
class_data.head()

Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                             frog, frog, newt, toad

In [13]:
# Load the testing data

zoo_data = pd.read_csv(r'C:\Users\macks\Project 4\Zoo_Data_Project\Resources\zoo.csv')
zoo_data.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

# Zoo Data Cleaning

In [14]:
# Find duplicates in the dataset.
duplicates = zoo_data[zoo_data.duplicated(subset='animal_name')]
print(duplicates)

   animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
26        frog     0         0     1     0         0        1         1   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
26        1         1         1         1     0     4     0         0   

    catsize  class_type  
26        0           5  


In [15]:
# Drop duplicates
zoo_data.drop_duplicates(subset='animal_name', inplace=True)
zoo_data.head(30)


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0     aardvark     1         0     0     1         0        0         1   
1     antelope     1         0     0     1         0        0         0   
2         bass     0         0     1     0         0        1         1   
3         bear     1         0     0     1         0        0         1   
4         boar     1         0     0     1         0        0         1   
5      buffalo     1         0     0     1         0        0         0   
6         calf     1         0     0     1         0        0         0   
7         carp     0         0     1     0         0        1         0   
8      catfish     0         0     1     0         0        1         1   
9         cavy     1         0     0     1         0        0         0   
10     cheetah     1         0     0     1         0        0         1   
11     chicken     0         1     1     0         1        0         0   
12        chub     0         0     1     0         0        1         1   
13        clam     0         0     1     0         0        0         1   
14        crab     0         0     1     0         0        1         1   
15    crayfish     0         0     1     0         0        1         1   
16        crow     0         1     1     0         1        0         1   
17        deer     1         0     0     1         0        0         0   
18     dogfish     0         0     1     0         0        1         1   
19     dolphin     0         0     0     1         0        1         1   
20        dove     0         1     1     0         1        0         0   
21        duck     0         1     1     0         1        1         0   
22    elephant     1         0     0     1         0        0         0   
23    flamingo     0         1     1     0         1        0         0   
24        flea     0         0     1     0         0        0         0   
25        frog     0         0     1     0         0        1         1   
27    fruitbat     1         0     0     1         1        0         0   
28     giraffe     1         0     0     1         0        0         0   
29        girl     1         0     0     1         0        0         1   
30        gnat     0         0     1     0         1        0         0   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0         1         1         1         0     0     4     0         0   
1         1         1         1         0     0     4     1         0   
2         1         1         0         0     1     0     1         0   
3         1         1         1         0     0     4     0         0   
4         1         1         1         0     0     4     1         0   
5         1         1         1         0     0     4     1         0   
6         1         1         1         0     0     4     1         1   
7         1         1         0         0     1     0     1         1   
8         1         1         0         0     1     0     1         0   
9         1         1         1         0     0     4     0         1   
10        1         1         1         0     0     4     1         0   
11        0         1         1         0     0     2     1         1   
12        1         1         0         0     1     0     1         0   
13        0         0         0         0     0     0     0         0   
14        0         0         0         0     0     4     0         0   
15        0         0         0         0     0     6     0         0   
16        0         1         1         0     0     2     1         0   
17        1         1         1         0     0     4     1         0   
18        1         1         0         0     1     0     1         0   
19        1         1         1         0     1     0     1         0   
20        0         1         1         0     0     2     1         1   
21        0         1         1         0     0     2     1         0  

In [16]:
# Remove the vampire from the dataset.
zoo_data = zoo_data[zoo_data['animal_name'] != 'vampire']

In [17]:
# Rename the animal_name "girl" to "human".
zoo_data.loc[zoo_data['animal_name'] == 'girl', 'animal_name'] = 'human'
zoo_data.head(30)

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0     aardvark     1         0     0     1         0        0         1   
1     antelope     1         0     0     1         0        0         0   
2         bass     0         0     1     0         0        1         1   
3         bear     1         0     0     1         0        0         1   
4         boar     1         0     0     1         0        0         1   
5      buffalo     1         0     0     1         0        0         0   
6         calf     1         0     0     1         0        0         0   
7         carp     0         0     1     0         0        1         0   
8      catfish     0         0     1     0         0        1         1   
9         cavy     1         0     0     1         0        0         0   
10     cheetah     1         0     0     1         0        0         1   
11     chicken     0         1     1     0         1        0         0   
12        chub     0         0     1     0         0        1         1   
13        clam     0         0     1     0         0        0         1   
14        crab     0         0     1     0         0        1         1   
15    crayfish     0         0     1     0         0        1         1   
16        crow     0         1     1     0         1        0         1   
17        deer     1         0     0     1         0        0         0   
18     dogfish     0         0     1     0         0        1         1   
19     dolphin     0         0     0     1         0        1         1   
20        dove     0         1     1     0         1        0         0   
21        duck     0         1     1     0         1        1         0   
22    elephant     1         0     0     1         0        0         0   
23    flamingo     0         1     1     0         1        0         0   
24        flea     0         0     1     0         0        0         0   
25        frog     0         0     1     0         0        1         1   
27    fruitbat     1         0     0     1         1        0         0   
28     giraffe     1         0     0     1         0        0         0   
29       human     1         0     0     1         0        0         1   
30        gnat     0         0     1     0         1        0         0   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0         1         1         1         0     0     4     0         0   
1         1         1         1         0     0     4     1         0   
2         1         1         0         0     1     0     1         0   
3         1         1         1         0     0     4     0         0   
4         1         1         1         0     0     4     1         0   
5         1         1         1         0     0     4     1         0   
6         1         1         1         0     0     4     1         1   
7         1         1         0         0     1     0     1         1   
8         1         1         0         0     1     0     1         0   
9         1         1         1         0     0     4     0         1   
10        1         1         1         0     0     4     1         0   
11        0         1         1         0     0     2     1         1   
12        1         1         0         0     1     0     1         0   
13        0         0         0         0     0     0     0         0   
14        0         0         0         0     0     4     0         0   
15        0         0         0         0     0     6     0         0   
16        0         1         1         0     0     2     1         0   
17        1         1         1         0     0     4     1         0   
18        1         1         0         0     1     0     1         0   
19        1         1         1         0     1     0     1         0   
20        0         1         1         0     0     2     1         1   
21        0         1         1         0     0     2     1         0  

In [18]:
# Check the datatypes of the dataset.
zoo_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  99 non-null     object
 1   hair         99 non-null     int64 
 2   feathers     99 non-null     int64 
 3   eggs         99 non-null     int64 
 4   milk         99 non-null     int64 
 5   airborne     99 non-null     int64 
 6   aquatic      99 non-null     int64 
 7   predator     99 non-null     int64 
 8   toothed      99 non-null     int64 
 9   backbone     99 non-null     int64 
 10  breathes     99 non-null     int64 
 11  venomous     99 non-null     int64 
 12  fins         99 non-null     int64 
 13  legs         99 non-null     int64 
 14  tail         99 non-null     int64 
 15  domestic     99 non-null     int64 
 16  catsize      99 non-null     int64 
 17  class_type   99 non-null     int64 
dtypes: int64(17), object(1)
memory usage: 14.7+ KB


In [19]:
# Change the datatype of the boolean columns to bool.
boolean_columns = ['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'tail', 'domestic', 'catsize']
zoo_data[boolean_columns] = zoo_data[boolean_columns].astype(bool)

In [20]:
zoo_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  99 non-null     object
 1   hair         99 non-null     bool  
 2   feathers     99 non-null     bool  
 3   eggs         99 non-null     bool  
 4   milk         99 non-null     bool  
 5   airborne     99 non-null     bool  
 6   aquatic      99 non-null     bool  
 7   predator     99 non-null     bool  
 8   toothed      99 non-null     bool  
 9   backbone     99 non-null     bool  
 10  breathes     99 non-null     bool  
 11  venomous     99 non-null     bool  
 12  fins         99 non-null     bool  
 13  legs         99 non-null     int64 
 14  tail         99 non-null     bool  
 15  domestic     99 non-null     bool  
 16  catsize      99 non-null     bool  
 17  class_type   99 non-null     int64 
dtypes: bool(15), int64(2), object(1)
memory usage: 4.5+ KB


In [21]:
# Reset the index of the DataFrame.
zoo_data = zoo_data.reset_index(drop=True)
zoo_data.head(30)

animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0     aardvark   True     False  False   True     False    False      True   
1     antelope   True     False  False   True     False    False     False   
2         bass  False     False   True  False     False     True      True   
3         bear   True     False  False   True     False    False      True   
4         boar   True     False  False   True     False    False      True   
5      buffalo   True     False  False   True     False    False     False   
6         calf   True     False  False   True     False    False     False   
7         carp  False     False   True  False     False     True     False   
8      catfish  False     False   True  False     False     True      True   
9         cavy   True     False  False   True     False    False     False   
10     cheetah   True     False  False   True     False    False      True   
11     chicken  False      True   True  False      True    False     False   
12        chub  False     False   True  False     False     True      True   
13        clam  False     False   True  False     False    False      True   
14        crab  False     False   True  False     False     True      True   
15    crayfish  False     False   True  False     False     True      True   
16        crow  False      True   True  False      True    False      True   
17        deer   True     False  False   True     False    False     False   
18     dogfish  False     False   True  False     False     True      True   
19     dolphin  False     False  False   True     False     True      True   
20        dove  False      True   True  False      True    False     False   
21        duck  False      True   True  False      True     True     False   
22    elephant   True     False  False   True     False    False     False   
23    flamingo  False      True   True  False      True    False     False   
24        flea  False     False   True  False     False    False     False   
25        frog  False     False   True  False     False     True      True   
26    fruitbat   True     False  False   True      True    False     False   
27     giraffe   True     False  False   True     False    False     False   
28       human   True     False  False   True     False    False      True   
29        gnat  False     False   True  False      True    False     False   

    toothed  backbone  breathes  venomous   fins  legs   tail  domestic  \
0      True      True      True     False  False     4  False     False   
1      True      True      True     False  False     4   True     False   
2      True      True     False     False   True     0   True     False   
3      True      True      True     False  False     4  False     False   
4      True      True      True     False  False     4   True     False   
5      True      True      True     False  False     4   True     False   
6      True      True      True     False  False     4   True      True   
7      True      True     False     False   True     0   True      True   
8      True      True     False     False   True     0   True     False   
9      True      True      True     False  False     4  False      True   
10     True      True      True     False  False     4   True     False   
11    False      True      True     False  False     2   True      True   
12     True      True     False     False   True     0   True     False   
13    False     False     False     False  False     0  False     False   
14    False     False     False     False  False     4  False     False   
15    False     False     False     False  False     6  False     False   
16    False      True      True     False  False     2   True     False   
17     True      True      True     False  False     4   True     False   
18     True      True     False     False   True     0   True     False   
19     True      True      True     False   True     0   True     False   
20    Fal

In [22]:
# Drop the columns "catsize" and "domestic" from the dataset.
zoo_data.drop(['catsize', 'domestic'], axis=1, inplace=True)

# Rename the column "breathes" to "air_breather".
zoo_data.rename(columns={'breathes': 'air_breather'}, inplace=True)
zoo_data.head()

animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0    aardvark   True     False  False   True     False    False      True   
1    antelope   True     False  False   True     False    False     False   
2        bass  False     False   True  False     False     True      True   
3        bear   True     False  False   True     False    False      True   
4        boar   True     False  False   True     False    False      True   

   toothed  backbone  air_breather  venomous   fins  legs   tail  class_type  
0     True      True          True     False  False     4  False           1  
1     True      True          True     False  False     4   True           1  
2     True      True         False     False   True     0   True           4  
3     True      True          True     False  False     4  False           1  
4     True      True          True     False  False     4   True           1

In [23]:
# Create a new column called "water_breather" and set it to True if the animal breathes water.
zoo_data['water_breather'] = np.where(zoo_data['class_type'].isin([4, 5]), True, False)
zoo_data.head()


animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0    aardvark   True     False  False   True     False    False      True   
1    antelope   True     False  False   True     False    False     False   
2        bass  False     False   True  False     False     True      True   
3        bear   True     False  False   True     False    False      True   
4        boar   True     False  False   True     False    False      True   

   toothed  backbone  air_breather  venomous   fins  legs   tail  class_type  \
0     True      True          True     False  False     4  False           1   
1     True      True          True     False  False     4   True           1   
2     True      True         False     False   True     0   True           4   
3     True      True          True     False  False     4  False           1   
4     True      True          True     False  False     4   True           1   

   water_breather  
0           False  
1           False  
2            True  
3           False  
4           False

In [24]:
# Create a new column order
reorder_columns = ['animal_name', 'class_type', 'hair', 'feathers', 'eggs'
                   , 'milk', 'airborne', 'aquatic', 'predator', 'toothed'
                    , 'backbone', 'air_breather', 'water_breather', 'venomous'
                    , 'fins', 'tail', 'legs']

# Reorder the columns
zoo_data = zoo_data.reindex(columns=reorder_columns)

# Print the updated DataFrame
zoo_data.head()

animal_name  class_type   hair  feathers   eggs   milk  airborne  aquatic  \
0    aardvark           1   True     False  False   True     False    False   
1    antelope           1   True     False  False   True     False    False   
2        bass           4  False     False   True  False     False     True   
3        bear           1   True     False  False   True     False    False   
4        boar           1   True     False  False   True     False    False   

   predator  toothed  backbone  air_breather  water_breather  venomous   fins  \
0      True     True      True          True           False     False  False   
1     False     True      True          True           False     False  False   
2      True     True      True         False            True     False   True   
3      True     True      True          True           False     False  False   
4      True     True      True          True           False     False  False   

    tail  legs  
0  False     4  
1   True     4  
2   True     0  
3  False     4  
4   True     4

In [30]:
# Add a new row to the DataFrame.
new_row = {'animal_name': 'salamander', 'class_type': 5, 'hair': False, 'feathers': False, 'eggs': True, 'milk': False, 'airborne': False, 'aquatic': True, 'predator': True, 'toothed': True, 'backbone': True, 'air_breather': True, 'water_breather': True, 'venomous': False, 'fins': False, 'tail': True, 'legs': 4}
zoo_data = zoo_data.append(new_row, ignore_index=True)
zoo_data.tail()

AttributeError: 'DataFrame' object has no attribute 'append'

# Class Data Cleaning

In [31]:
# Remove one of the frogs from the list
class_data.loc[4, 'Animal_Names'] = class_data.loc[4, 'Animal_Names'].replace('frog,', '')

class_data.loc[4, 'Animal_Names'] += ', frog, salamander'

class_data.head()


Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [32]:
# Replace Number of Animal Species in Class under mammals with 40
class_data.loc[0, 'Number_Of_Animal_Species_In_Class'] = 40

class_data.head()

Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 40     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [33]:
# Remove vampire and girl from the record and replace it with human
class_data.loc[0, 'Animal_Names'] = class_data.loc[0, 'Animal_Names'].replace(
    'vampire,', '').replace('girl,', '') + ', human'

class_data.head()


Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 40     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [34]:
# Define features set
X = zoo_data.copy()
X.drop("animal_name", axis=1, inplace=True)
X.head()

class_type   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0           1   True     False  False   True     False    False      True   
1           1   True     False  False   True     False    False     False   
2           4  False     False   True  False     False     True      True   
3           1   True     False  False   True     False    False      True   
4           1   True     False  False   True     False    False      True   

   toothed  backbone  air_breather  water_breather  venomous   fins   tail  \
0     True      True          True           False     False  False  False   
1     True      True          True           False     False  False   True   
2     True      True         False            True     False   True   True   
3     True      True          True           False     False  False  False   
4     True      True          True           False     False  False   True   

   legs  
0     4  
1     4  
2     0  
3     4  
4     4

In [35]:
 # Define target vector
y = zoo_data["class_type"].values.reshape(-1, 1)
y[:5]


array([[1],
       [1],
       [4],
       [1],
       [1]], dtype=int64)

In [36]:
# Split the training data into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [39]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)


In [40]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [41]:
# Initialize the Decision Tree model
dt_model = DecisionTreeClassifier()

In [42]:
# Train the Decision Tree model
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [43]:
# Make predictions on the validation set
y_val_pred = dt_model.predict(X_test)

In [44]:
# Evaluate the model on the validation set
accuracy = accuracy_score(y_test, y_val_pred)
conf_matrix = confusion_matrix(y_test, y_val_pred)
classification_rep = classification_report(y_test, y_val_pred)

In [45]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 1.0
Confusion Matrix:
[[11  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  2  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  3]]
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         3

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [46]:
# Make predictions on the test set
y_test_pred = dt_model.predict(X_test)

In [47]:
# Evaluate the model on the test set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)
test_classification_rep = classification_report(y_test, y_test_pred)

In [48]:

print("\nTest Set Results:")
print(f"Accuracy: {test_accuracy}")
print(f"Confusion Matrix:\n{test_conf_matrix}")
print(f"Classification Report:\n{test_classification_rep}")


Test Set Results:
Accuracy: 1.0
Confusion Matrix:
[[11  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  2  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  3]]
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         3

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# PyCaret

In [49]:
from pycaret.classification import save_model
from pycaret.classification import *
import pandas as pd

In [60]:
big_zoo = pd.read_csv(r"C:\Users\macks\Project 4\Zoo_Data_Project\Resources\merged_extended_data.csv")
#animal_input= pd.read_csv("./animal_database.animals.csv")

In [61]:
s = setup(big_zoo, target="class_type", train_size=0.8)

In [62]:
best = compare_models()

In [63]:
print(best)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=3080, solver='auto',
                tol=0.0001)


In [64]:
finalize_model(best)

Pipeline(memory=Memory(location=None),
         steps=[('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None, include=['legs'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean'...
                                    transformer=TargetEncoder(cols=['animal_name'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0))),
                ('actual_estimator',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=3080,
                                 solver='auto', tol=0.0001))],
         verbose=False)

In [65]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [66]:
from IPython.display import display
# Display the full preview of the output
print(predict_model(best))


           animal_name    Class_Name   hair  feathers   eggs   milk  airborne  \
2     african_elephant        Mammal   True     False  False   True     False   
182               pika        Mammal   True     False   True  False     False   
246  tarantula_gazelle       Reptile  False     False   True  False     False   
203               rhea          Bird  False      True   True  False     False   
71                 emu          Bird  False      True   True  False      True   
150           marmoset        Mammal   True     False   True  False      True   
124         java_tiger        Mammal   True     False  False   True     False   
263             walrus        Mammal   True     False  False   True     False   
190          porcupine        Mammal   True     False  False   True     False   
30                carp          Fish  False     False   True  False     False   
87             giraffe        Mammal   True     False  False   True     False   
245          tarantula  Inve

In [67]:
# Create an ensemble model
ensemble_model = ensemble_model(best)

In [68]:
# Evaluate the ensemble model
evaluate_model(ensemble_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [69]:
tuned_ensemble_model = tune_model(ensemble_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [70]:
evaluate_model(tuned_ensemble_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [71]:
predict_model(tuned_ensemble_model)

animal_name    Class_Name   hair  feathers   eggs   milk  airborne  \
2     african_elephant        Mammal   True     False  False   True     False   
182               pika        Mammal   True     False   True  False     False   
246  tarantula_gazelle       Reptile  False     False   True  False     False   
203               rhea          Bird  False      True   True  False     False   
71                 emu          Bird  False      True   True  False      True   
150           marmoset        Mammal   True     False   True  False      True   
124         java_tiger        Mammal   True     False  False   True     False   
263             walrus        Mammal   True     False  False   True     False   
190          porcupine        Mammal   True     False  False   True     False   
30                carp          Fish  False     False   True  False     False   
87             giraffe        Mammal   True     False  False   True     False   
245          tarantula  Invertebrate  False     False   True  False     False   
126        javan_tiger        Mammal   True     False  False   True     False   
78                 fox        Mammal   True     False  False   True     False   
170              otter        Mammal   True     False  False   True     False   
80            fruitbat        Mammal   True     False  False   True      True   
137               lark          Bird  False      True   True  False      True   
97                gull          Bird  False      True   True  False      True   
23                boar        Mammal   True     False  False   True     False   
201          red_panda        Mammal   True     False  False   True     False   
230        sperm_whale        Mammal   True     False  False   True     False   
262           wallaroo        Mammal   True     False  False   True     False   
141               lion        Mammal   True     False  False   True     False   
113              hyena        Mammal   True     False  False   True     False   
29             caracal        Mammal   True     False  False   True     False   
274                yak        Mammal   True     False  False   True     False   
41          chinchilla        Mammal   True     False  False   True     False   
106       hippopotamus        Mammal   True     False  False   True     False   
222              sloth        Mammal   True     False  False   True     False   
199                rat        Mammal   True     False   True  False     False   
271               worm  Invertebrate  False     False   True  False     False   
117       iguana_moose        Mammal   True     False  False   True     False   
136           ladybird           Bug  False     False   True  False      True   
176     parrot_penguin          Bird  False      True   True  False      True   
224           slowworm       Reptile  False     False   True  False     False   
110           housefly           Bug   True     False   True  False      True   
6            armadillo        Mammal   True     False   True  False     False   
198            raccoon        Mammal   True     False  False   True     False   
160               newt     Amphibian  False     False   True  False     False   
118    indian_elephant        Mammal   True     False  False   True     False   
70       elephant_seal        Mammal   True     False  False   True     False   
12          bali_tiger        Mammal   True     False  False   True     False   
260            vulture          Bird  False      True   True  False      True   
83             gazelle        Mammal   True     False  False   True     False   
88       giraffe_snake       Reptile  False     False   True  False     False   
191           porpoise        Mammal  False     False  False   True     False   
232           squirrel        Mammal   True     False  False   True     False   
139              lemur        Mammal   True     False  False   True     False   
62           dromedary        Mammal   Tru

In [72]:
dt = create_model("dt", fold = 20)
print("DT Model Created")
tuned_dt = tune_model(dt)
print("DT Tuned Model Created")

DT Model Created


Fitting 10 folds for each of 10 candidates, totalling 100 fits
DT Tuned Model Created


In [73]:
rf = create_model("rf", fold = 5) #Random Forest
tuned_rf = tune_model(rf) #tuned Random Forest

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [74]:
gbc = create_model("gbc", fold = 5) #Gradient Boosting
tuned_gbc = tune_model(gbc)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [75]:
rf = create_model("rf", fold = 5) #exta trees
tuned_rf = tune_model(rf)
save_model(tuned_rf, 'tuned_rf_model')


Fitting 10 folds for each of 10 candidates, totalling 100 fits
Transformation Pipeline and Model Successfully Saved


(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None, include=['legs'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'...
                  RandomForestClassifier(bootstrap=False, ccp_alpha=0.0,
                                         class_weight='balanced_subsample',
                    

In [76]:
lr = create_model("lr", fold = 5) #Extreme Gradient Boosting
tuned_lr = tune_model(lr)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [77]:

rg = create_model("ridge", fold=5) # Ridge Classifier
tuned_rg = tune_model(rg)


Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [78]:
# Add SVM model
svm = create_model('svm')

# Tune SVM model
tuned_svm = tune_model(svm)
save_model(tuned_svm, 'tuned_svm_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Transformation Pipeline and Model Successfully Saved


(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None, include=['legs'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'...
                  SGDClassifier(alpha=0.02, average=False, class_weight=None,
                                early_stopping=False, epsilon=0.1, eta0=0.4,
              

In [79]:
# Add LightGBM model
lightgbm = create_model('lightgbm')

# Tune the LightGBM model
tuned_lightgbm = tune_model(lightgbm)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [80]:
evaluate_model(svm)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…