<a href="https://colab.research.google.com/github/danielimorgan/Zoo_Data_Project/blob/Lara/project_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [312]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [313]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import tree

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Needed for decision tree visualization
import pydotplus
from IPython.display import Image


In [314]:
# Load the training data

class_data = pd.read_csv('/content/drive/MyDrive/class.csv')
class_data.head()

Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                             frog, frog, newt, toad

In [315]:
# Load the zoo data

zoo_data = pd.read_csv('/content/drive/MyDrive/zoo.csv')
zoo_data.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [316]:
additional_df = pd.read_csv('/content/drive/MyDrive/zoo_extended_list_cleaned.csv')
additional_df.head()

animal_name  class_type  hair  feathers   eggs   milk  airborne  \
0          aardvark           1  True     False  False   True     False   
1          aardwolf           1  True     False  False   True     False   
2  african_elephant           1  True     False  False   True     False   
3         alligator           3  True     False   True  False     False   
4            alpaca           1  True     False  False   True     False   

   aquatic  predator  toothed  backbone  air_breather  water_breather  \
0    False      True     True      True          True           False   
1    False      True     True      True          True           False   
2    False     False     True      True          True           False   
3     True      True     True      True          True           False   
4    False     False     True      True          True           False   

   venomous   fins   tail  legs  
0     False  False  False     4  
1     False  False   True     4  
2     False  False   True     4  
3     False   True   True     4  
4     False  False   True     4

# Zoo Data Cleaning

In [317]:
# Find duplicates in the dataset.
duplicates = zoo_data[zoo_data.duplicated(subset='animal_name')]
print(duplicates)

   animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
26        frog     0         0     1     0         0        1         1   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
26        1         1         1         1     0     4     0         0   

    catsize  class_type  
26        0           5  


In [318]:
# Drop duplicates
zoo_data.drop_duplicates(subset='animal_name', inplace=True)



In [319]:
# Remove the vampire from the dataset.
zoo_data = zoo_data[zoo_data['animal_name'] != 'vampire']

In [320]:
# Rename the animal_name "girl" to "human".
zoo_data.loc[zoo_data['animal_name'] == 'girl', 'animal_name'] = 'human'


In [321]:
# Check the datatypes of the dataset.
zoo_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  99 non-null     object
 1   hair         99 non-null     int64 
 2   feathers     99 non-null     int64 
 3   eggs         99 non-null     int64 
 4   milk         99 non-null     int64 
 5   airborne     99 non-null     int64 
 6   aquatic      99 non-null     int64 
 7   predator     99 non-null     int64 
 8   toothed      99 non-null     int64 
 9   backbone     99 non-null     int64 
 10  breathes     99 non-null     int64 
 11  venomous     99 non-null     int64 
 12  fins         99 non-null     int64 
 13  legs         99 non-null     int64 
 14  tail         99 non-null     int64 
 15  domestic     99 non-null     int64 
 16  catsize      99 non-null     int64 
 17  class_type   99 non-null     int64 
dtypes: int64(17), object(1)
memory usage: 14.7+ KB


In [322]:
# Change the datatype of the boolean columns to bool.
boolean_columns = ['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'tail', 'domestic', 'catsize']
zoo_data[boolean_columns] = zoo_data[boolean_columns].astype(bool)

In [323]:
zoo_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  99 non-null     object
 1   hair         99 non-null     bool  
 2   feathers     99 non-null     bool  
 3   eggs         99 non-null     bool  
 4   milk         99 non-null     bool  
 5   airborne     99 non-null     bool  
 6   aquatic      99 non-null     bool  
 7   predator     99 non-null     bool  
 8   toothed      99 non-null     bool  
 9   backbone     99 non-null     bool  
 10  breathes     99 non-null     bool  
 11  venomous     99 non-null     bool  
 12  fins         99 non-null     bool  
 13  legs         99 non-null     int64 
 14  tail         99 non-null     bool  
 15  domestic     99 non-null     bool  
 16  catsize      99 non-null     bool  
 17  class_type   99 non-null     int64 
dtypes: bool(15), int64(2), object(1)
memory usage: 4.5+ KB


In [324]:
# Reset the index of the DataFrame.
zoo_data = zoo_data.reset_index(drop=True)
zoo_data.head(5)

animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0    aardvark   True     False  False   True     False    False      True   
1    antelope   True     False  False   True     False    False     False   
2        bass  False     False   True  False     False     True      True   
3        bear   True     False  False   True     False    False      True   
4        boar   True     False  False   True     False    False      True   

   toothed  backbone  breathes  venomous   fins  legs   tail  domestic  \
0     True      True      True     False  False     4  False     False   
1     True      True      True     False  False     4   True     False   
2     True      True     False     False   True     0   True     False   
3     True      True      True     False  False     4  False     False   
4     True      True      True     False  False     4   True     False   

   catsize  class_type  
0     True           1  
1     True           1  
2    False           4  
3     True           1  
4     True           1

In [325]:
# Drop the columns "catsize" and "domestic" from the dataset.
zoo_data.drop(['catsize', 'domestic'], axis=1, inplace=True)

# Rename the column "breathes" to "air_breather".
zoo_data.rename(columns={'breathes': 'air_breather'}, inplace=True)
zoo_data.head()

animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0    aardvark   True     False  False   True     False    False      True   
1    antelope   True     False  False   True     False    False     False   
2        bass  False     False   True  False     False     True      True   
3        bear   True     False  False   True     False    False      True   
4        boar   True     False  False   True     False    False      True   

   toothed  backbone  air_breather  venomous   fins  legs   tail  class_type  
0     True      True          True     False  False     4  False           1  
1     True      True          True     False  False     4   True           1  
2     True      True         False     False   True     0   True           4  
3     True      True          True     False  False     4  False           1  
4     True      True          True     False  False     4   True           1

In [326]:
# Create a new column called "water_breather" and set it to True if the animal breathes water.
zoo_data['water_breather'] = np.where(zoo_data['class_type'].isin([4, 5]), True, False)
zoo_data.head()


animal_name   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0    aardvark   True     False  False   True     False    False      True   
1    antelope   True     False  False   True     False    False     False   
2        bass  False     False   True  False     False     True      True   
3        bear   True     False  False   True     False    False      True   
4        boar   True     False  False   True     False    False      True   

   toothed  backbone  air_breather  venomous   fins  legs   tail  class_type  \
0     True      True          True     False  False     4  False           1   
1     True      True          True     False  False     4   True           1   
2     True      True         False     False   True     0   True           4   
3     True      True          True     False  False     4  False           1   
4     True      True          True     False  False     4   True           1   

   water_breather  
0           False  
1           False  
2            True  
3           False  
4           False

In [327]:
# Create a new column order
reorder_columns = ['animal_name', 'class_type', 'hair', 'feathers', 'eggs'
                   , 'milk', 'airborne', 'aquatic', 'predator', 'toothed'
                    , 'backbone', 'air_breather', 'water_breather', 'venomous'
                    , 'fins', 'tail', 'legs']

# Reorder the columns
zoo_data = zoo_data.reindex(columns=reorder_columns)

# Print the updated DataFrame
zoo_data.head()

animal_name  class_type   hair  feathers   eggs   milk  airborne  aquatic  \
0    aardvark           1   True     False  False   True     False    False   
1    antelope           1   True     False  False   True     False    False   
2        bass           4  False     False   True  False     False     True   
3        bear           1   True     False  False   True     False    False   
4        boar           1   True     False  False   True     False    False   

   predator  toothed  backbone  air_breather  water_breather  venomous   fins  \
0      True     True      True          True           False     False  False   
1     False     True      True          True           False     False  False   
2      True     True      True         False            True     False   True   
3      True     True      True          True           False     False  False   
4      True     True      True          True           False     False  False   

    tail  legs  
0  False     4  
1   True     4  
2   True     0  
3  False     4  
4   True     4

In [328]:
# Add a new row to the DataFrame.
new_row = {'animal_name': 'salamander', 'class_type': 5, 'hair': False, 'feathers': False, 'eggs': True, 'milk': False, 'airborne': False, 'aquatic': True, 'predator': True, 'toothed': True, 'backbone': True, 'air_breather': True, 'water_breather': True, 'venomous': False, 'fins': False, 'tail': True, 'legs': 4}
zoo_data = zoo_data.append(new_row, ignore_index=True)
zoo_data.tail()

animal_name  class_type   hair  feathers   eggs   milk  airborne  aquatic  \
95        wasp           6   True     False   True  False      True    False   
96        wolf           1   True     False  False   True     False    False   
97        worm           7  False     False   True  False     False    False   
98        wren           2  False      True   True  False      True    False   
99  salamander           5  False     False   True  False     False     True   

    predator  toothed  backbone  air_breather  water_breather  venomous  \
95     False    False     False          True           False      True   
96      True     True      True          True           False     False   
97     False    False     False          True           False     False   
98     False    False      True          True           False     False   
99      True     True      True          True            True     False   

     fins   tail  legs  
95  False  False     6  
96  False   True     4  
97  False  False     0  
98  False   True     2  
99  False   True     4

# Class Data Cleaning

In [329]:
# Remove one of the frogs from the list
class_data.loc[4, 'Animal_Names'] = class_data.loc[4, 'Animal_Names'].replace('frog,', '')

class_data.loc[4, 'Animal_Names'] += ', frog, salamander'

class_data.head()


Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [330]:
# Replace Number of Animal Species in Class under mammals with 40
class_data.loc[0, 'Number_Of_Animal_Species_In_Class'] = 40

class_data.head()

Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 40     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [331]:
# Remove vampire and girl from the record and replace it with human
class_data.loc[0, 'Animal_Names'] = class_data.loc[0, 'Animal_Names'].replace(
    'vampire,', '').replace('girl,', '') + ', human'

class_data.head()


Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 40     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

# Zoo/Class Data Merge

In [332]:
# Rename columns to match zoo_data
class_data = class_data.rename(columns={'Class_Type': 'Class_Name', 'Class_Number': 'class_type'})
class_data.head()

class_type  Number_Of_Animal_Species_In_Class Class_Name  \
0           1                                 40     Mammal   
1           2                                 20       Bird   
2           3                                  5    Reptile   
3           4                                 13       Fish   
4           5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                       newt, toad, frog, salamander

In [333]:
# Merge the two DataFrames.
merged_df = pd.merge(zoo_data, class_data, how='left', on=["class_type", "class_type"])
merged_df.head()

animal_name  class_type   hair  feathers   eggs   milk  airborne  aquatic  \
0    aardvark           1   True     False  False   True     False    False   
1    antelope           1   True     False  False   True     False    False   
2        bass           4  False     False   True  False     False     True   
3        bear           1   True     False  False   True     False    False   
4        boar           1   True     False  False   True     False    False   

   predator  toothed  backbone  air_breather  water_breather  venomous   fins  \
0      True     True      True          True           False     False  False   
1     False     True      True          True           False     False  False   
2      True     True      True         False            True     False   True   
3      True     True      True          True           False     False  False   
4      True     True      True          True           False     False  False   

    tail  legs  Number_Of_Animal_Species_In_Class Class_Name  \
0  False     4                                 40     Mammal   
1   True     4                                 40     Mammal   
2   True     0                                 13       Fish   
3  False     4                                 40     Mammal   
4   True     4                                 40     Mammal   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  aardvark, antelope, bear, boar, buffalo, calf,...  
2  bass, carp, catfish, chub, dogfish, haddock, h...  
3  aardvark, antelope, bear, boar, buffalo, calf,...  
4  aardvark, antelope, bear, boar, buffalo, calf,...

In [334]:
# Drop the extra columns
columns_to_drop = ['Number_Of_Animal_Species_In_Class', 'Animal_Names']
merged_df = merged_df.drop(columns=columns_to_drop)
merged_df.head()

animal_name  class_type   hair  feathers   eggs   milk  airborne  aquatic  \
0    aardvark           1   True     False  False   True     False    False   
1    antelope           1   True     False  False   True     False    False   
2        bass           4  False     False   True  False     False     True   
3        bear           1   True     False  False   True     False    False   
4        boar           1   True     False  False   True     False    False   

   predator  toothed  backbone  air_breather  water_breather  venomous   fins  \
0      True     True      True          True           False     False  False   
1     False     True      True          True           False     False  False   
2      True     True      True         False            True     False   True   
3      True     True      True          True           False     False  False   
4      True     True      True          True           False     False  False   

    tail  legs Class_Name  
0  False     4     Mammal  
1   True     4     Mammal  
2   True     0       Fish  
3  False     4     Mammal  
4   True     4     Mammal

In [335]:
# Reorder columns
new_columns = ['animal_name', 'Class_Name','class_type', 'hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'air_breather', 'water_breather', 'venomous', 'fins', 'tail', 'legs']
merged_df = merged_df.reindex(columns=new_columns)
merged_df.head()


animal_name Class_Name  class_type   hair  feathers   eggs   milk  airborne  \
0    aardvark     Mammal           1   True     False  False   True     False   
1    antelope     Mammal           1   True     False  False   True     False   
2        bass       Fish           4  False     False   True  False     False   
3        bear     Mammal           1   True     False  False   True     False   
4        boar     Mammal           1   True     False  False   True     False   

   aquatic  predator  toothed  backbone  air_breather  water_breather  \
0    False      True     True      True          True           False   
1    False     False     True      True          True           False   
2     True      True     True      True         False            True   
3    False      True     True      True          True           False   
4    False      True     True      True          True           False   

   venomous   fins   tail  legs  
0     False  False  False     4  
1     False  False   True     4  
2     False   True   True     0  
3     False  False  False     4  
4     False  False   True     4

In [336]:
# Read the CSV file containing additional rows into a new DataFrame
additional_df = pd.read_csv('/content/drive/MyDrive/corrected_animal.csv',sep=',')
print(additional_df.shape)
additional_df.info()

(82, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   animal_name     82 non-null     object
 1   Class_Name      82 non-null     object
 2   class_type      82 non-null     int64 
 3   hair            82 non-null     bool  
 4   feathers        82 non-null     bool  
 5   eggs            82 non-null     bool  
 6   milk            82 non-null     bool  
 7   airborne        82 non-null     bool  
 8   aquatic         82 non-null     bool  
 9   predator        82 non-null     bool  
 10  toothed         82 non-null     bool  
 11  backbone        82 non-null     bool  
 12  air_breather    82 non-null     bool  
 13  water_breather  82 non-null     bool  
 14  venomous        82 non-null     bool  
 15  fins            82 non-null     bool  
 16  tail            82 non-null     bool  
 17  legs            82 non-null     int64 
dtypes: 

In [337]:
# Concatenate the original DataFrame with the new DataFrame containing additional rows
merged_data = pd.concat([merged_df, additional_df], ignore_index=True)
print(merged_data.shape)
# Optionally, reset the index of the concatenated DataFrame
merged_data.reset_index(drop=True, inplace=True)

# Print the concatenated DataFrame
merged_data.head()

(182, 18)


animal_name Class_Name  class_type   hair  feathers   eggs   milk  airborne  \
0    aardvark     Mammal           1   True     False  False   True     False   
1    antelope     Mammal           1   True     False  False   True     False   
2        bass       Fish           4  False     False   True  False     False   
3        bear     Mammal           1   True     False  False   True     False   
4        boar     Mammal           1   True     False  False   True     False   

   aquatic  predator  toothed  backbone  air_breather  water_breather  \
0    False      True     True      True          True           False   
1    False     False     True      True          True           False   
2     True      True     True      True         False            True   
3    False      True     True      True          True           False   
4    False      True     True      True          True           False   

   venomous   fins   tail  legs  
0     False  False  False     4  
1     False  False   True     4  
2     False   True   True     0  
3     False  False  False     4  
4     False  False   True     4

In [217]:
# prompt: give me the unique count of the class_name column

#unique_class_names = merged_data['Class_Name'].unique()
#print(f"Number of unique class names: {unique_class_names}")
#filter_bug= merged_data[(merged_data['Class_Name']=='Bug')]
#filter_bug

In [218]:
#filtered_data = merged_data.filter(['air_breather'==False & 'water_breather'==False])
#filtered_df = merged_data[(merged_data['air_breather'] ==False) & (merged_data['water_breather'] ==  False)]
#filtered_df

In [338]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   animal_name     182 non-null    object
 1   Class_Name      182 non-null    object
 2   class_type      182 non-null    int64 
 3   hair            182 non-null    bool  
 4   feathers        182 non-null    bool  
 5   eggs            182 non-null    bool  
 6   milk            182 non-null    bool  
 7   airborne        182 non-null    bool  
 8   aquatic         182 non-null    bool  
 9   predator        182 non-null    bool  
 10  toothed         182 non-null    bool  
 11  backbone        182 non-null    bool  
 12  air_breather    182 non-null    bool  
 13  water_breather  182 non-null    bool  
 14  venomous        182 non-null    bool  
 15  fins            182 non-null    bool  
 16  tail            182 non-null    bool  
 17  legs            182 non-null    int64 
dtypes: bool(14

In [220]:
#Add animal_name and Class_Name to a new dataframe.
animal_name_list = merged_data['animal_name'].tolist()
class_name_list = merged_data['Class_Name'].tolist()

animal_list_df = pd.DataFrame({'animal_name': animal_name_list, 'Class_Name': class_name_list})


In [339]:
# Drop animal_name from merged_data
merged_data = merged_data.drop(columns=['animal_name'])
merged_data.head()
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Class_Name      182 non-null    object
 1   class_type      182 non-null    int64 
 2   hair            182 non-null    bool  
 3   feathers        182 non-null    bool  
 4   eggs            182 non-null    bool  
 5   milk            182 non-null    bool  
 6   airborne        182 non-null    bool  
 7   aquatic         182 non-null    bool  
 8   predator        182 non-null    bool  
 9   toothed         182 non-null    bool  
 10  backbone        182 non-null    bool  
 11  air_breather    182 non-null    bool  
 12  water_breather  182 non-null    bool  
 13  venomous        182 non-null    bool  
 14  fins            182 non-null    bool  
 15  tail            182 non-null    bool  
 16  legs            182 non-null    int64 
dtypes: bool(14), int64(2), object(1)
memory usage: 6.9+ KB

# Decision Tree Model

In [340]:
# Define features set
X = merged_data.copy()
X.drop(["Class_Name", "class_type"], axis=1, inplace=True)
X.head()

hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0   True     False  False   True     False    False      True     True   
1   True     False  False   True     False    False     False     True   
2  False     False   True  False     False     True      True     True   
3   True     False  False   True     False    False      True     True   
4   True     False  False   True     False    False      True     True   

   backbone  air_breather  water_breather  venomous   fins   tail  legs  
0      True          True           False     False  False  False     4  
1      True          True           False     False  False   True     4  
2      True         False            True     False   True   True     0  
3      True          True           False     False  False  False     4  
4      True          True           False     False  False   True     4

In [341]:
 # Define target vector
y = merged_data["Class_Name"].values.reshape(-1, 1)
y[:5]


array([['Mammal'],
       ['Mammal'],
       ['Fish'],
       ['Mammal'],
       ['Mammal']], dtype=object)

In [342]:
# Split the training data into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [343]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [344]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)


In [345]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [346]:
# Initialize the Decision Tree model
dt_model = DecisionTreeClassifier()

In [347]:
#Check the data types of X_train and y_train:
print(f"X_train data type: {type(X_train)}")
print(f"y_train data type: {type(y_train)}")

X_train data type: <class 'pandas.core.frame.DataFrame'>
y_train data type: <class 'numpy.ndarray'>


In [348]:
#convert y_train to a dataframe
y_train = pd.DataFrame(y_train)

In [349]:
print(f"Number of missing values in X_train: {X_train.isnull().sum().sum()}")
print(f"Number of missing values in y_train: {y_train.isnull().sum().sum()}")

Number of missing values in X_train: 0
Number of missing values in y_train: 0


In [351]:
# Train the Decision Tree model
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=None, splitter='best')

In [352]:
# Make predictions on the validation set
y_val_pred = dt_model.predict(X_test)

In [353]:
# Evaluate the model on the validation set
accuracy = accuracy_score(y_test, y_val_pred)
conf_matrix = confusion_matrix(y_test, y_val_pred)
classification_rep = classification_report(y_test, y_val_pred)

In [354]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.9459459459459459
Confusion Matrix:
[[ 1  0  0  0  0  0  2]
 [ 0 10  0  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  3  0  0]
 [ 0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  3]]
Classification Report:
              precision    recall  f1-score   support

   Amphibian       1.00      0.33      0.50         3
        Bird       1.00      1.00      1.00        10
         Bug       1.00      1.00      1.00         3
        Fish       1.00      1.00      1.00         3
Invertebrate       1.00      1.00      1.00         3
      Mammal       1.00      1.00      1.00        12
     Reptile       0.60      1.00      0.75         3

    accuracy                           0.95        37
   macro avg       0.94      0.90      0.89        37
weighted avg       0.97      0.95      0.94        37



In [355]:
# Make predictions on the test set
y_test_pred = dt_model.predict(X_test)

In [356]:
# Evaluate the model on the test set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)
test_classification_rep = classification_report(y_test, y_test_pred)

In [358]:

print("\nTest Set Results:")
print(f"Accuracy: {test_accuracy}")
print(f"Confusion Matrix:\n{test_conf_matrix}")
print(f"Classification Report:\n{test_classification_rep}")


Test Set Results:
Accuracy: 0.9459459459459459
Confusion Matrix:
[[ 1  0  0  0  0  0  2]
 [ 0 10  0  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  3  0  0]
 [ 0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  3]]
Classification Report:
              precision    recall  f1-score   support

   Amphibian       1.00      0.33      0.50         3
        Bird       1.00      1.00      1.00        10
         Bug       1.00      1.00      1.00         3
        Fish       1.00      1.00      1.00         3
Invertebrate       1.00      1.00      1.00         3
      Mammal       1.00      1.00      1.00        12
     Reptile       0.60      1.00      0.75         3

    accuracy                           0.95        37
   macro avg       0.94      0.90      0.89        37
weighted avg       0.97      0.95      0.94        37



In [359]:
# Create DOT data

dot_data = tree.export_graphviz(
    dt_model, out_file=None, feature_names=X.columns, class_names=dt_model.classes_, filled=True
)

# Draw graph
graph = pydotplus.graph_from_dot_data(dot_data)

# Show graph
Image(graph.create_png())


SVM Model

In [361]:
# Fit to the training data and validate with the test data
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(X_train, y_train)
predictions = model.predict(X_test)
#print(X_test)
predictions

array(['Mammal', 'Bird', 'Mammal', 'Bird', 'Mammal', 'Invertebrate',
       'Bug', 'Mammal', 'Bird', 'Mammal', 'Bug', 'Reptile', 'Mammal',
       'Mammal', 'Invertebrate', 'Bird', 'Amphibian', 'Bird',
       'Invertebrate', 'Bird', 'Fish', 'Bird', 'Mammal', 'Mammal',
       'Mammal', 'Bird', 'Fish', 'Fish', 'Reptile', 'Mammal', 'Reptile',
       'Bird', 'Reptile', 'Bird', 'Mammal', 'Bug', 'Reptile'],
      dtype=object)

In [362]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

   Amphibian       1.00      0.33      0.50         3
        Bird       1.00      1.00      1.00        10
         Bug       1.00      1.00      1.00         3
        Fish       1.00      1.00      1.00         3
Invertebrate       1.00      1.00      1.00         3
      Mammal       1.00      1.00      1.00        12
     Reptile       0.60      1.00      0.75         3

    accuracy                           0.95        37
   macro avg       0.94      0.90      0.89        37
weighted avg       0.97      0.95      0.94        37



# PyCaret

In [363]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [364]:
!pip install pycaret

In [365]:
!pip install mlflow

In [366]:
updated_merged_data = merged_data.drop(columns="class_type",  axis=1)
updated_merged_data.shape

(182, 16)

In [ ]:
# prompt: print count values of Class_Name

class_count = merged_data['Class_Name'].value_counts()
#print(class_count)
merged_data.head()
merged_data.shape

In [367]:
from pycaret.classification import *

s = setup(updated_merged_data, target="Class_Name")

# also try the code below
# s = setup(df, target="class_type")

In [ ]:
best = compare_models()

In [369]:
print(best)

[]


In [370]:
finalize_model(best[0])

IndexError: list index out of range

In [371]:
print(f"The 'best' list contains {len(best)} items:")
for item in best:
    print(item)

The 'best' list contains 0 items:


In [ ]:
evaluate_model(best)

In [ ]:
predict_model(best)

In [ ]:
from pycaret.classification import *

#s = setup(merged_df, target="class_type")
s = setup(merged_data, target="Class_Name")

# also try the code below
# s = setup(df, target="class_type")

In [ ]:
best = compare_models()

In [ ]:
print(best)

In [ ]:
finalize_model(best)

In [ ]:
evaluate_model(best)

In [ ]:
predict_model(best)

In [ ]:
dt = create_model("dt", fold = 5)


In [ ]:
rf = create_model("dt", fold = 5) #Random Forest

In [ ]:
gbc = create_model("gbc", fold = 5) #Gradient Boosting

In [ ]:
et = create_model("et", fold = 5) #exta trees

In [ ]:
xgboost = create_model("xgboost", fold = 5) #Extreme Gradient Boosting

In [ ]:
nb = create_model("nb", fold = 5) #naive Bayes

In [ ]:
tuned_nb = tuned_model(nb)